export enum ROLE {
  ADMIN = 'ADMIN',
  USER = 'USER',
  MODERATOR = 'MODERATOR',
}

export enum GENDER {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
}

export enum RELATIONSHIP_STATUS {
  SINGLE = 'SINGLE',
  IN_RELATION = 'IN_RELATION',
}

export enum ACCOUNT_STATUS {
  ACTIVATED = 'ACTIVATED',
  BLOCKED = 'BLOCKED',
}
